{% set name = "array_record" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [py<310]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}    # [unix]
    - {{ compiler('cxx') }}  # [unix]
  host:
    - python
    - pip
  run:
    - python
    - absl-py
    - etils
    - libgcc-ng      # [linux]
    - libstdcxx-ng   # [linux]

test:
  imports:
    - array_record
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/array_record
  summary: A file format that achieves a new frontier of IO efficiency
  description: |
    ArrayRecord is a new file format derived from Riegeli, achieving a new frontier of IO efficiency.
    We designed ArrayRecord to support parallel read, write, and random access by record index.
    ArrayRecord builds on top of Riegeli and supports the same compression algorithms.
  license: Apache-2.0
  license_family: Apache
  dev_url: https://github.com/google/array_record
  doc_url: https://github.com/google/array_record

extra:
  recipe-maintainers:
    - steven
